package org.bouncycastle.tls.test;

import java.security.MessageDigest;
import java.security.PrivateKey;
import java.security.SecureRandom;
import java.security.Signature;

import org.bouncycastle.jsl.test.JslTestProvider;
import org.bouncycastle.tls.Certificate;
import org.bouncycastle.tls.DigitallySigned;
import org.bouncycastle.tls.HashAlgorithm;
import org.bouncycastle.tls.ProtocolVersion;
import org.bouncycastle.tls.SignatureAlgorithm;
import org.bouncycastle.tls.SignatureAndHashAlgorithm;
import org.bouncycastle.tls.TlsCredentialedSigner;
import org.bouncycastle.tls.crypto.TlsCertificate;
import org.bouncycastle.tls.crypto.TlsCryptoParameters;
import org.bouncycastle.tls.crypto.TlsVerifier;
import org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto;
import org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCryptoProvider;
import org.bouncycastle.util.Strings;
import org.bouncycastle.util.encoders.Hex;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * DSA TLS credentials against a provider that may refuse to sign with them.
 * <p>
 * A FIPS module can be built with {@code dsa-sign-disabled}: DSA keys still import and DSA
 * signatures still verify, but signing is refused at {@code initSign}. The Signature service stays
 * registered - it has to, or verification would go too - so no service lookup can tell the two
 * apart. Both branches below are live in this fork: the 3.5.8 module refuses, JSL and the 3.1.2
 * module sign.
 */
public class TlsDsaCredentialCapabilityTest
{
    private static final String CERT = "x509-server-dsa.pem";
    private static final String KEY = "x509-server-key-dsa.pem";

    /** Signed once under JSL with NoneWithDSA over the SHA-256 digest of MESSAGE. */
    private static final byte[] PINNED_SIGNATURE = Hex.decode(
        "3045022100868705f87571bbc99c6ace57579f1df2ea65afdc3dc083f04eb4fae07a54727e"
            + "022039b349e28950e015611136e4a0311651213330d821d90a21520f6cbe22b60839");

    private static final byte[] MESSAGE = Strings.toByteArray("JSL DSA verify-only pin");

    private JcaTlsCrypto crypto;

    @Before
    public void setUp()
    {
        JslTestProvider.install();
        crypto = (JcaTlsCrypto)new JcaTlsCryptoProvider()
            .setProvider(JslTestProvider.provider()).create(new SecureRandom());
    }

    /**
     * The credential is refused when it is loaded, not mid-handshake. Where the provider can sign,
     * the same load succeeds and the signature it produces verifies through the certificate.
     */
    @Test
    public void aDsaCredentialIsRefusedAtLoadWhereTheProviderCannotSign()
        throws Exception
    {
        SignatureAndHashAlgorithm sha256WithDsa =
            SignatureAndHashAlgorithm.getInstance(HashAlgorithm.sha256, SignatureAlgorithm.dsa);

        if (!providerCanSignWithTheFixtureKey())
        {
            try
            {
                loadCredential(sha256WithDsa);
                fail("a DSA credential was accepted by a provider that cannot sign with it");
            }
            catch (IllegalArgumentException e)
            {
                assertTrue("the refusal does not state the constraint: " + e.getMessage(),
                    e.getMessage().indexOf("cannot sign with this provider") >= 0);
            }
            return;
        }

        TlsCredentialedSigner credential = loadCredential(sha256WithDsa);
        assertNotNull("no DSA credential was loaded", credential);

        byte[] hash = digest(MESSAGE);
        byte[] signature = credential.generateRawSignature(hash);

        TlsCertificate certificate = credential.getCertificate().getCertificateAt(0);
        TlsVerifier verifier = certificate.createVerifier(SignatureAlgorithm.dsa);
        assertTrue("the signature this credential produced did not verify",
            verifier.verifyRawSignature(new DigitallySigned(sha256WithDsa, signature), hash));
    }

    /**
     * Verification is the half that survives {@code dsa-sign-disabled}, so it is asserted on every
     * configuration against a signature pinned in this file rather than one generated by the run.
     */
    @Test
    public void aPinnedDsaSignatureVerifiesOnEveryConfiguration()
        throws Exception
    {
        TlsCertificate certificate = TlsTestUtils.loadCertificateResource(crypto, CERT);
        TlsVerifier verifier = certificate.createVerifier(SignatureAlgorithm.dsa);

        SignatureAndHashAlgorithm sha256WithDsa =
            SignatureAndHashAlgorithm.getInstance(HashAlgorithm.sha256, SignatureAlgorithm.dsa);

        assertTrue("the pinned DSA signature did not verify", verifier.verifyRawSignature(
            new DigitallySigned(sha256WithDsa, PINNED_SIGNATURE), digest(MESSAGE)));
    }

    private TlsCredentialedSigner loadCredential(SignatureAndHashAlgorithm algorithm)
        throws Exception
    {
        TlsCryptoParameters cryptoParams = new TlsCryptoParameters(null)
        {
            public ProtocolVersion getServerVersion()
            {
                return ProtocolVersion.TLSv12;
            }
        };

        return TlsTestUtils.loadSignerCredentials(cryptoParams, crypto,
            new String[]{ CERT }, KEY, algorithm);
    }

    /** The real question: will this provider sign with this key, not does it list the service. */
    private boolean providerCanSignWithTheFixtureKey()
        throws Exception
    {
        PrivateKey key = TlsTestUtils.loadJcaPrivateKeyResource(crypto, KEY);
        try
        {
            Signature signature = Signature.getInstance("NoneWithDSA", JslTestProvider.name());
            signature.initSign(key);
            return true;
        }
        catch (java.security.InvalidKeyException e)
        {
            return false;
        }
    }

    private byte[] digest(byte[] message)
        throws Exception
    {
        return MessageDigest.getInstance("SHA-256", JslTestProvider.name()).digest(message);
    }
}
